blank_issues_enabled: false
contact_links:
  - name: Questions and Discussions
    url: https://github.com/bytedance/android-inline-hook/discussions
    about: Looking for help. Discuss general issues.
